site_name: Pylho Documentation
theme: readthedocs
docs_dir: sources
#repo_url: https://gitlab.com/longubu/batchio.git
#site_url: need-site
# theme_dir: theme
site_description: 'Boblob Law.'

dev_addr: '127.0.0.1:8000'
google_analytics: ['UA-61785484-1', '[pylho].io']


pages:
- Home: index.md
- Alerts: alerts.md
- Colors: colors.md
- Terminal: terminal.md
- Debug: debug.md
- Log_Off_User: log_off_user.md